### ISSUE TITLE
Installation instructions for WSL

### ISSUE THREAD

**Issue by tdelmas** [canonical/ubuntu.com#10644]
The current instruction only links to the Microsoft store (which is not always available and require a Microsoft account)

A new section "how to install manually without the Microsoft Store" could be added and links to the Microsoft documentation [Manual installation steps - Downloading distributions](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions)

Or - better - reproduce the necessary steps:

- Using the command line:

  `Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile Ubuntu.appx -UseBasicParsing`

- Using the graphical interface:
 1. Go to https://aka.ms/wslubuntu2004, it will download an .appx file.
 2. Open that file, it will ask if you want to install it.

Source: https://askubuntu.com/questions/1369653/how-to-install-ubuntu-wsl-on-windows-11-without-a-microsoft-account

---
*Reported from: https://ubuntu.com/wsl*

**Comment by petesfrench** [comment]
I reached out to Oliver Smith and he is going to communicate this with the technical author responsible for the WSL docs page

**Comment by edibotopic** [comment]
This is addressed in https://github.com/ubuntu/WSL/pull/492 .

It's good to have this mentioned in the Ubuntu WSL documentation now because of its importance to some users.
At the same time, we try not to duplicate material already found in the Microsoft WSL docs, so we have provided links as appropriate.

Lastly, we need to be careful when indicating that images can be downloaded from sources that we do not directly maintain because of the difficulties this would present from a support perspective.
