### ISSUE TITLE
Alternate Arch download link is incorrect on certificates.

### ISSUE THREAD

**Issue by bladernr** [canonical/ubuntu.com#11584]
While looking up some stuff for a different issue I filed, I discovered that download links for PowerPC and s390x systems point to https://ubuntu.com/download/server which is incorrect... ARM certificates have a download button that points correctly to their arch specific landing page...

s390x: https://ubuntu.com/certified/201909-27363
ppc64le: https://ubuntu.com/certified/201805-26248

Those are examples and in each case they point to the AMD64 server landing page.

Each of those, like ARM, should point to the appropriate arch specific pages instead:

s390x: https://ubuntu.com/download/server/s390x
ppc64le: https://ubuntu.com/download/server/power

**Comment by nottrobin** [comment]
The model details pages like are generic, and at present they simply use the "category" to display the download link:

https://github.com/canonical-web-and-design/ubuntu.com/blob/f822b9ee491539a9b5d9a7548ab2a7ebf66762ca/templates/certified/model-details.html#L88-L101

Is the solution here to add categories to the certifications API for "s390x" and "power" (or "ppc64le") and extend our template to provide those download links too? The other option, I suppose, is to ask the certifications API to always provide a download URL with these items?

@codersquid do you have any input on this?

**Comment by codersquid** [comment]
Category is different than architecture, and we don't use architecture for the categories. We don't store download urls for certificates, I guess that's something you could handle in the template by checking for the architecture or something we could hardcode on our side. Since you already have the logic to construct the download links, would you consider keeping it on your side and checking for the arch for server pages? The logic could live in the views instead of the template. I think there used to be some utility code that did that, but it's gone now.

**Comment by carkod** [comment]
> Category is different than architecture, and we don't use architecture for the categories. We don't store download urls for certificates, I guess that's something you could handle in the template by checking for the architecture or something we could hardcode on our side. Since you already have the logic to construct the download links, would you consider keeping it on your side and checking for the arch for server pages? The logic could live in the views instead of the template. I think there used to be some utility code that did that, but it's gone now.

I'll create a PR with that utility code. I'll let you guys know when it's ready for review
