### ISSUE TITLE
Empty takeover on u.com

### ISSUE THREAD

**Issue by anasereijo** [canonical/ubuntu.com#11651]
<img width="1680" alt="Screenshot 2022-05-26 at 17 07 18" src="https://user-images.githubusercontent.com/36884067/170528300-df58e50a-370f-4494-b6b8-c779f736ec00.png">

---
*Reported from: https://ubuntu.com/*

**Comment by sowasred2012** [comment]
I've fixed the takeover - the image was refusing to load, I think because of the filename "ad7c61ba-ezgif.com-gif-maker+%281%29.jpg"

I've replaced it with one that doesn't feature a url in the filename - but it's not great that we showed an empty takeover, we should either not show the takeover at all, or only show the text if the image doesn't load for whatever reason. Currently we wait for the image to load before removing a class that reveals everything at once, if the image doesn't load the class is never removed.

**Comment by carkod** [comment]
This seems to be fixed.
