### ISSUE TITLE
Clear/explicit dates on the support flow chart

### ISSUE THREAD

**Issue by pponnuvel** [canonical/ubuntu.com#12253]
Various EOL/support dates in this page are in a chart format where the exact date isn't clear at all. Even finding the month when a specific support ends isn't easy.

Can this page be modified so that the specific dates are available.  For example, if you hover over the bars, if it could show the end date, that'd be good.

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by petesfrench** [comment]
@al-bakalova What do you think of adding an 'on hover' to each of the bars that displays a more exact end date?

**Comment by al-bakalova** [comment]
Hey @petesfrench 
I do agree this information is really heard to read. I am not even sure if a horizontal bar chart is the right way to present the info. I would normally go for a small table that is easier to read.
A quick fix would be to show the end month on hover. I think adding the month to the chart itself would be even better. Something short and sweet like  "Apr 2029". Since the graph shows every other year, we need both the month and the year.
We may also confirm this with someone from the visual team, to make sure we follow their guidelines.

**Comment by britneywwc** [comment]
The support release cycle page has been updated since the date of this issue creation. We implemented more interactive horizontal bar charts to address this issue (see screenshot below). Closing this ticket as resolved, thanks!

<img width="1005" alt="Screenshot 2024-07-24 at 3 03 18 PM" src="https://github.com/user-attachments/assets/4b7c9876-59db-4cb4-9c75-8d16f0d8539f">
