### ISSUE TITLE
Instructions for Installing Docker in LXD has a missing line Continuation  for the CURL command

### ISSUE THREAD

**Issue by bmullan** [canonical/ubuntu.com#12601]
The bash line in the Instructions needs a Continuation indicator at the end of the CURL command line
 
Now we need to add Docker’s official GPG key:

**
Is now:

> **curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg**
> -**-dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg**

**

**
Should be:

> **curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg** \ 
> **--dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg**

**

**Comment by tbille** [comment]
hi @bmullan thanks for bringing this issue to our attention. Could you please provide a link to the page you saw this issue? Thanks

**Comment by mionaalex** [comment]
Similar to my reply on the other related issue, this particular section of the tutorial followed the instructions from the [official Docker installation page](https://docs.docker.com/engine/install/ubuntu/) and it doesn't include the continuation indicator. When I initially tested it, I had no issues, but perhaps things changed. Will test out the tutorial and adjust. Thanks again for the feedback.

**Comment by britneywwc** [comment]
Hi @mionaalex, were the tutorials updated? Please feel free to close this issue if this has been resolved.

**Comment by britneywwc** [comment]
The [tutorial](https://ubuntu.com/tutorials/how-to-run-docker-inside-lxd-containers#3-install-docker) has since been updated to include the continuation indicator (attached screenshot below). Closing this issue as resolved. Thanks everyone!
<img width="871" alt="Screenshot 2024-07-25 at 2 15 10 PM" src="https://github.com/user-attachments/assets/b7749a81-1571-4363-86c6-233388011ad4">
