### ISSUE TITLE
Download Ubuntu Core - link refers to Core 20 image. Core 22 available..

### ISSUE THREAD

**Issue by gerbrent** [canonical/ubuntu.com#13025]
Download Ubuntu Core - link refers to Core 20 image. Core 22 available..

![image](https://github.com/canonical/ubuntu.com/assets/7018928/e0a64518-6b32-4bb1-81d0-6c608665a604)

instructions suggest `Download the [Ubuntu Core 20 image for amd64](https://cdimage.ubuntu.com/ubuntu-core/20/stable/current/ubuntu-core-20-amd64.img.xz).`

However, there's a more recent version of Ubuntu Core available: Ubuntu Core 22. Thus:

* `Download the [Ubuntu Core 20 image for amd64](https://cdimage.ubuntu.com/ubuntu-core/20/stable/current/ubuntu-core-20-amd64.img.xz).` -> `Download the [Ubuntu Core 22 image for amd64](https://cdimage.ubuntu.com/ubuntu-core/22/stable/current/ubuntu-core-22-amd64.img.xz).`

* `Uncompress the image with the following command:  unxz ubuntu-core-20-amd64.img.xz` -> `Uncompress the image with the following command:  unxz ubuntu-core-22-amd64.img.xz` 

(also, in general, the exhaustive Ubuntu Core download offering is difficult to find.. only got to the possibilities via URL modification. This [daily build directory](https://cdimage.ubuntu.com/ubuntu-core/22/stable/current/) is what I was searching for! And presents far more install options than the [Core](https://ubuntu.com/core) or [IoT](https://ubuntu.com/download/iot) pages....)

Thanks!

---
*Reported from: https://ubuntu.com/download/kvm*

**Comment by britneywwc** [comment]
Thanks for flagging @gerbrent! I believe the docs have been updated since the published date of this issue thus I'll be closing it for now. Please feel free to reopen this issue or leave a comment directly on the [Discourse post](https://discourse.ubuntu.com/t/get-started-with-ubuntu-core/19737?_gl=1*soalux*_gcl_au*MTg2NDMyMTcxLjE3MTg2ODE3OTQ.&_ga=2.156214011.1304205652.1721617739-452497310.1710905626) where the docs are pulled from.
