### ISSUE TITLE
Payment Page does not accept german Postal Code

### ISSUE THREAD

**Issue by icerootsvw** [canonical/ubuntu.com#13122]
I wanted to order Ubuntu Pro and on the payment Page i entered Germany as my country and for the postal code i entered 38226 which is the code of our city "Salzgitter" but the webpage is telling me that the postal/zip code is not valid, so i can not finish the payment process (because i need the correct address on the bill)

---
*Reported from: https://ubuntu.com/account/checkout*

**Comment by icerootsvw** [comment]
it is also not possible to enter a german VAT number (DE followed by 9 numbers like DE123456789)

**Comment by albertkol** [comment]
Thank you for raising an issue. 

You mention two problems:
1. **The post code being rejected for the card.** Stripe is our provider that manages payments at the moment, it is responsible for validating user inputs. If the card is rejected, it's because certain security checks Stripe does are not passing. A common issue is that the zip code provided is not matching the card. For security reasons I recommend to reach to customersuccess@canonical.com to get better help for payment related problems.
2. **German VAT number.** Thank you for mentioning this one. Apparently there is indeed a bug with the VAT which at times it will reject VAT numbers. We are working to fix it. Meanwhile there are two options: either try again later or proceed without adding a VAT.
