### ISSUE TITLE
Mirror no longer receiving traffic

### ISSUE THREAD

**Issue by futzel** [canonical/ubuntu.com#13343]
Hi,

ubuntu.com seems to be no longer redirecting download requests to
the mirror I maintain:

https://launchpad.net/ubuntu/+mirror/releases.ubuntu.repulsive.eu

I'm seeing loss of traffic starting around Oct 25th.

I also reported this to mirrors@ubuntu.com but was referred to here:

https://rt.ubuntu.com/Ticket/Display.html?id=76851

This was an issue several years ago as well, back then it turned out to
be a general problem:

https://rt.ubuntu.com/Ticket/Display.html?id=34579

Thanks.

**Comment by PhirePhly** [comment]
I've also seen this issue across the entire mm.fcix.net mirror fleet, where all ubuntu-releases traffic disappeared in late October and we haven't been serving the ISOs from any of our 32 mirrors since then.

Is this expected behavior?

**Comment by PhirePhly** [comment]
Should I still bother to provision new Linux mirrors for /ubuntu-releases/ or is Canonical no longer interested in using community mirrors to distribute ISO images?

**Comment by MrXermon** [comment]
Same issue with out mirror, traffic stopped end of October last year. Any clear communication would be great!

**Comment by james58899** [comment]
After looking at the network requests, I found that [mirrors.json?local=True](https://ubuntu.com/mirrors.json?local=True) responded with an empty list, but [mirrors.json](https://ubuntu.com/mirrors.json) did have many mirrors available.

Is this a bug or intentional? It looks like something went wrong while generating the local mirror list.

**Comment by james58899** [comment]
After looking at the source code, the part that generates json has not been changed for a long time.
Maybe it is due to infrastructure changes? The backend cannot obtain the correct client IP?

https://github.com/canonical/ubuntu.com/blob/823bca2179235b78250eddfaf0646b08925ea3bf/webapp/views.py#L50-L92

**Comment by akbarkz** [comment]
The Sites team is planning to have a look and hopefully fix this issue soon. We'll update you on the outcome.

**Comment by PhirePhly** [comment]
![image](https://github.com/canonical/ubuntu.com/assets/131002/ff97f25c-25b7-460e-a1e6-ec6050d4b5b2)

I see /ubuntu-releases/ traffic hitting mirrors as of about nine hours ago, so something changed!

**Comment by 0xEmma** [comment]
> ![image](https://private-user-images.githubusercontent.com/131002/327627147-ff97f25c-25b7-460e-a1e6-ec6050d4b5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDA0MzAsIm5iZiI6MTcxNDcwMDEzMCwicGF0aCI6Ii8xMzEwMDIvMzI3NjI3MTQ3LWZmOTdmMjVjLTI1YjctNDYwZS1hMWU2LWVjNjA1MGQ0YjViMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwMTM1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTE5MTJlNDJhZmQ3YWI2NGQzM2ViNGViNWM1M2U3N2IwZWY5MWMzMjgxMmFiZGM3MWY1YzhmOWQyM2NiZTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KdVJmdE0PhbAi0ZB8qsKR5S7MjEnOfd41cMDOZJd9No)
> 
> I see /ubuntu-releases/ traffic hitting mirrors as of about nine hours ago, so something changed!

Likewise here as of about ~11am EST
![image](https://github.com/canonical/ubuntu.com/assets/47154306/309252c1-9295-4c4e-a6b1-0384d162ce31)

**Comment by akbarkz** [comment]
@quantum-mirror unfortunately, we cannot get a user's location by their IP. There is a content-cache behind our websites that changes users' IPs to local ones making it impossible to geolocate them. That's why we introduced a workaround by using users' timezone of their browser, which I agree is not 100% accurate, but is way better than nothing.

**Comment by forkwhilefork** [comment]
@akbarkz this warrants a separate issue, and as this doesn't affect me I'm declining to create it, but surely you can get the users' real IP behind the cache via the [X-Forwarded-For header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)?
