### ISSUE TITLE
possible error in nodejs for jammy, CVE-2023-4807

### ISSUE THREAD

**Issue by greengeko** [canonical/ubuntu.com#13664]
For nodejs for jammy it is marked as "needed" instead of not vulnerable. What does it mean? Is it intended? Could you please correct it if it is the case that it is an error or could you explain me the reason for the "needed"?
---
*Reported from: https://ubuntu.com/security/CVE-2023-4807*

**Comment by dodys** [comment]
hey @greengeko 
that was a mistake. I've just fixed and it should be reflected on the website in a few minutes.
For any other issues or doubts with CVE status I recommend sending an email to the Ubuntu Security team on security@ubuntu.com since we don't get to see the issues listed here as they are specific to the website and not the information that goes to it.

**Comment by dodys** [comment]
This issue can be closed now

**Comment by mtruj013** [comment]
Thanks @dodys , closing
