### ISSUE TITLE
Wrong Openstack table

### ISSUE THREAD

**Issue by token47** [canonical/ubuntu.com#14128]
The release cycle table for openstack seems wrong.

1. It is missing Zed which is one of the intermediary releases between Yoga and Caracal.
2. 2024.1 is Caracal which is an LTS release, and it is marked as it if was a normal one.
3. The fact that Zed is missing and Caracal/2024.1 is not marked as LTS makes it seem like it's just another intermediary release (although the long bar for the support time says otherwise)

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by token47** [comment]
Also, it is understandable that it might not be called LTS because it was not released yet, but it is confusing enough that the long bar on that one indicates it IS supported for a long time.

Also, it appears it was released in April which was not true, the charms were but because of delays in Ceph bits we are not installing it in customers yet, but they see this table and question it.

**Comment by token47** [comment]
Also, while I totally agree that the new names are now numbers and they are the official names and we should use them instead, the names still exist and customers still like to refer to them, so maybe we should add the names after the numbers for completeness (like ex. "2024.1 / Caracal")

**Comment by token47** [comment]
Maybe Zed was removed to not create confusion with a release which support has already expired, but anyway, the table seems confusing as is (having Zed there with clear expired timeline would help customers to understand they need to migrate)

**Comment by tytus-kurek** [comment]
@token47 thanks for reaching out.

Please find my answers below:

- OpenStack Zed is EOL so it's been already removed from the diagram
- OpenStack 24.01 (Caracal) will only be available on Ubuntu 22.04 LTS through the Ubuntu Cloud Archive in Charmed OpenStack with a security and support commitment until April 2032. Thus, it won't be an LTS in the strict sense. OpenStack 24.01 (Caracal) will only be a proper LTS when deployed with Sunbeam. Please refer to [this discourse post](https://discourse.canonical.com/t/confidential-canonical-openstack-support-moving-forward/3674) and the [FAQ document](https://docs.google.com/document/d/1CAsbQ9WfH7luQ4estzQbDRdBPkydjxXWsHbAHeVoJzs/edit#heading=h.i93w42m4p1l6) for more information on this topic.
- You're right that OpenStack 24.01 (Caracal) has not been released yet in Charmed OpenStack, but the goal of this diagram is show future releases too so that customers/partners can understand how our release cycle looks like. We'll adjust the release date once the release is out.
- I appreciate your commentary on names vs numbers but the direction is to stick into the naming convention used by the upstream.

Please let me know if you have any further questions.

**Comment by token47** [comment]
Hi Tytus

Thank you for the responses. I understand. Just wanted to make sure those were not mistakes.

About the names vs numbers, the suggestion was to use both, not switch, but I also understand that we may want to use only primary official names.

You can consider this closed, thanks.

**Comment by immortalcodes** [comment]
Thanks for your responses.
