### ISSUE TITLE
links to hardware certification page are buried and not easy to find.

### ISSUE THREAD

**Issue by bladernr** [canonical/ubuntu.com#3918]
## Summary

link to the certification pages is buried in fine print and only appears a couple times on the new website (that took me way to long to find).

## Process

Go to ubuntu.com and try to find the Hardware Certification site link.  

## Current and expected result

In the past, Certification was a little easier to find.  Now it took me at least 5 minutes worth of clicking links and deep diving before I noticed a tiny little link to certification.ubuntu.com buried in the breadcrumbs of the "Enterprise" dropdown.  

Certification should be a LOT easier to find, especially since:

The Openstack page mentioned a huge list of certified hardware twice
The AI/ML page lists it once
The Support page lists it specifically with no link

The Datacenter page DOES have a link, however, it's buried on that page and isn't referenced at all on the parent page (dropdown when you click "Enterprise" as noted above) where it should be listed.

## Screenshot

I could add screen shots, if you wish, but there would be several, and the overall point is simply that the Hardware Certification site should be listed prominently on the dropdown when you click on "Enterprise" rather than as a breadcrumb hidden at the bottom.  

I have suggest a link under Datacenter along with the current links of 
Metal as a Service provisioning
Multi cloud operations]

by editing the source doc.

However, I also note that there is no link at all (that I could find) to the Devices Hardware Certification pages:

https://certification.ubuntu.com/desktop/
https://certification.ubuntu.com/iot/

Though some of that may be buried in links under "Internet of Things", to be honest, I didn't dig too deeply on that, I just wanted to mention it as it relates to this request too.

**Comment by tbille** [comment]
This will be a item for this cycle 20.10 https://github.com/canonical-web-and-design/master-epics/issues/122

**Comment by matthewpaulthomas** [comment]
[IA design](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.9u9dhxfo3euv) now ready for implementation: changing links in the “Enterprise” mega-menu, and adding internal links to the first two pages cited by @bladernr. (But not to /support, where there is currently no mention of certified hardware. I think that’s a wider issue best handled separately, for example whether it should also/instead be on /advantage or /pricing/infra.)

By a fortunate combination of three things —

- the new site will be at the same URL as it was a few years ago
- that URL currently redirects to the current site
- the redirect passes along URL parameters, but the current site ignores unknown URL parameters

— these links can be implemented before the rest of the sub-site is implemented. For now, “Ubuntu-certified workstations” will redirect to the certification site main page, but once the new sub-site is implemented, the link will go to the list of certified desktops.

**Comment by bladernr** [comment]
This completely fell off my radar, unfortunately, so apologies for so late a reply... especially since I don't have an answer for you, to be honest, especially since it seems others are looking at changes to navigation.  That said, it's very much something we are interested in, and Matias who is the new Certification Director has a keen interest in this as well.

**Comment by mz2** [comment]
I would second that it remains pretty difficult to find links to any of the server, desktop / laptop or IoT certification still, would love to learn about the wider plans here. Given the current organisation of the site I think it'd be reasonable to refer to the existence of certified servers, laptops and desktops, and IoT devices in the relevant sections on the front page. That is, link to some combo of https://ubuntu.com/certified/desktops, https://ubuntu.com/certified/laptops, https://ubuntu.com/certified/servers, and https://ubuntu.com/certified/devices from the relevant sections on the front page where there's talk about workstations, data centres and IoT, respectively.

As far as the current information hierarchy in the menus, putting my Ubuntu end user hat on and trying to find the links to the certification program, I have trouble parsing the site: I can find after  some digging links towards https://ubuntu.com/certified from under "Enterprise" right now, but I don't "Enterprise" is really the first thing that comes to mind, or inclusive of the usecases that the certified devices cover. It'd be lovely to see a "Hardware" option at the same level we've got "Download" (after all, buying certified hardware is the best way to experience Ubuntu).

**Comment by davegoddard42** [comment]
Thanks @bladernr, not a problem, we've been working away on this in the background.

@mz2 In terms of the homepage, this is something we could look at, but it's not on my radar right now. I do see your point, and the current homepage is ripe for an overhaul anyway. However, I have been working on the mega menu for a little while now - this isn't just a reorganisation but a complete redesign. We're about to start user testing our latest thinking.

In our current thinking, there will be multiple routes to Certified Hardware pages. Firstly, we're adding a new top level category that acts as both an inroduction to the OSs and the ability to download. For each section, we focus on an OS (desktop, server, installation on IoT devices etc) and we're placing links certified hardware within that structure, next to download. We're also looking at having Certified Hardware as a topic within a Products menu also.

All of these decisions is rooted in research we carried out with visitors to our site. We've going to validate our decisions with further user testing - so we'll have the best way to get users to where they want to go. We're due to build a prototype soon. Are you going to Frankfurt? We're looking to solicit some feedback from different areas of the business during the sprint, would be good to show you our current thinking in person.

**Comment by bladernr** [comment]
Unless something changes for the worst, I believe both of us are planning on attending in Frankfurt, as well as a couple others who may be interested in this as well.

**Comment by davegoddard42** [comment]
@bladernr awesome - will be great to meet you in person, you too @mz2.

**Comment by petesfrench** [comment]
Hi @bladernr, I followed you suggestion and tried to find 'Certified Hardware' from ubuntu.com and actually found it very easily. Here was my journey:
- land on the page and see 'Products' in the navigation
- the navigation opens and one of the tabs is 'Certified Hardware'
- click the tab and there is a number of links relating to 'Certified Hardware'

Obviously at the time this issue was created we had our old navigation. Do you think we can close this with the improvements to the navigation?

**Comment by petesfrench** [comment]
Closing issue as per above comment.
